sudo: required

language: go

go:
  - 1.9.1

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d
  # the current package is not up to date so we will build from the source
  # - wget -qO - http://packages.confluent.io/deb/3.3/archive.key | sudo apt-key add -
  # - sudo add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/3.3 stable main"
  # - sudo apt-get update
  # - sudo apt-get install librdkafka1 librdkafka-dev
  - git clone https://github.com/edenhill/librdkafka.git
  - cd librdkafka && ./configure && make && sudo make install

script:
  - go test -v ./request
  - go test -v ./response
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
