sudo: required

language: go

go:
  - 1.9.1

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

services:
  - docker

before_install:
  - docker run -p 4222:4222 -d nats

script:
  - go test -v ./request
  - go test -v ./response
  - go test --race -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
